apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance
  labels:
    app: insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance-container
        image: junaidm3699/insurance
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-np-service
  labels:
    app: insurance
spec:
  selector:
    app: insurance

  type: NodePort
  ports:
  - nodePort: 31055    
    port: 8081
    targetPort: 8081
